name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.5'

      - name: Install Visual Studio Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Clean (if needed)
        run: flutter clean

      - name: Install dependencies again
        run: flutter pub get

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Verify build output
        run: |
          Write-Host "Listing contents of build/windows/runner..."
          Get-ChildItem -Recurse -Path build/windows/runner

          $releasePath = "build/windows/runner/Release"
          if (-not (Test-Path -Path $releasePath)) {
              Write-Error "ERROR: Release folder not found after build!"
              exit 1
          }

          $exe = Get-ChildItem -Path $releasePath -Filter *.exe | Select-Object -First 1
          if (-not $exe) {
              Write-Error "ERROR: No .exe found in Release folder!"
              exit 1
          }

          Write-Host "Found executable: $($exe.FullName)"
        shell: pwsh

      - name: Rename Executable to STINO.exe
        run: |
          $releasePath = "build/windows/runner/Release"
          $exe = Get-ChildItem -Path $releasePath -Filter *.exe | Select-Object -First 1
          Rename-Item -Path $exe.FullName -NewName "STINO.exe"
          Write-Host "Renamed $($exe.Name) to STINO.exe"
        shell: pwsh

      - name: Zip Windows release
        run: |
          $zipPath = "stino_windows_build.zip"
          Compress-Archive -Path build/windows/runner/Release/* -DestinationPath $zipPath -Force
          Write-Host "Created archive $zipPath"
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: STINO_Windows_Build
          path: stino_windows_build.zip
