name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.5'

      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '17.0'
          install-packages: true
          install-components: 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Microsoft.VisualStudio.Component.Windows10SDK.20348'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: |
          flutter pub get
          flutter clean

      - name: Build with detailed logging
        run: |
          flutter build windows --release -v > build_log.txt 2>&1 || (cat build_log.txt && exit 1)
          cat build_log.txt
          if (-not (Test-Path -Path "build/windows/runner/Release")) {
              Write-Output "Build failed. Contents of build/windows:"
              Get-ChildItem -Path build/windows -Recurse
              exit 1
          }
        shell: pwsh

      - name: Rename Executable
        run: |
          $exePath = Join-Path -Path (Get-Item "build/windows/runner/Release/*.exe").FullName
          Rename-Item -Path $exePath -NewName "STINO.exe"
        shell: pwsh

      - name: Zip Windows release
        run: |
          Compress-Archive -Path build/windows/runner/Release/* -DestinationPath stino_windows_build.zip -Force
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: STINO_Windows_Build
          path: stino_windows_build.zip