name: Build and Package STINO for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Installer
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.5'

      - name: Install Visual Studio Build Tools
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Clean and rebuild
        run: |
          flutter clean
          flutter pub get
          flutter build windows --release

      - name: Verify Build Output
        run: |
          $releasePath = "build/windows/x64/runner/Release"
          if (-not (Test-Path -Path $releasePath)) {
              Write-Error "ERROR: Release folder not found at $releasePath!"
              exit 1
          }
          Get-ChildItem -Path $releasePath
          $exe = Get-ChildItem -Path $releasePath -Filter *.exe | Select-Object -First 1
          if (-not $exe) {
              Write-Error "ERROR: No .exe found in $releasePath!"
              exit 1
          }
          Rename-Item -Path $exe.FullName -NewName "STINO.exe" -Force
          Write-Host "✅ Renamed executable to STINO.exe"
        shell: pwsh

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Create Installer Script
        run: |
          $iss = @"
          [Setup]
          AppName=STINO
          AppVersion=1.0.0
          DefaultDirName={autopf}\STINO
          DefaultGroupName=STINO
          OutputDir=build\installer
          OutputBaseFilename=STINO_Installer
          Compression=lzma
          SolidCompression=yes
          WizardStyle=modern

          [Files]
          Source: "build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion

          [Icons]
          Name: "{group}\STINO"; Filename: "{app}\STINO.exe"
          Name: "{commondesktop}\STINO"; Filename: "{app}\STINO.exe"; Tasks: desktopicon

          [Tasks]
          Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"

          [Run]
          Filename: "{app}\STINO.exe"; Description: "Launch STINO"; Flags: nowait postinstall skipifsilent
          "@
          $iss | Out-File -FilePath "installer.iss" -Encoding UTF8
        shell: pwsh

      - name: Build Installer
        run: iscc installer.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: STINO_Windows_Installer
          path: build/installer/STINO_Installer.exe
