name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.5'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows

      - name: Debug release directory
        run: Get-ChildItem -Path build/windows/runner/Release

      - name: Rename Executable to STINO.exe
        run: |
          $exe = Get-ChildItem -Path build/windows/runner/Release -Filter *.exe | Select-Object -First 1
          Rename-Item -Path $exe.FullName -NewName STINO.exe
        shell: pwsh

      - name: Zip Windows release
        run: Compress-Archive -Path build/windows/runner/Release/* -DestinationPath stino_windows_build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: STINO_Windows_Build
          path: stino_windows_build.zip
